# Generated by Django 5.1.3 on 2025-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_leave_reportee_name_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavequota',
            old_name='total_quota',
            new_name='cl_quota',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='remain_quota',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='used_quota',
        ),
        migrations.AddField(
            model_name='leavequota',
            name='pl_quota',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavequota',
            name='sl_quota',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavequota',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
