# Generated by Django 5.1.3 on 2025-03-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
