# Generated by Django 5.1.3 on 2025-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_employee_department_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], default='Junior', max_length=10),
        ),
    ]
